[package]
name = "lang"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
name = "lang_core"

[dependencies]
colored = "3.0.0"

[[test]]
name = "compiler_language"
path = "tests/tests.rs"
